name: Analyse de sécurité avec Bandit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  bandit_scan:
    name: Exécuter Bandit sur le code Python
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation de Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Exécution de l’analyse Bandit
        run: |
          bandit -r . || true
          bandit -r . -f txt -o rapport_bandit.txt || true
          bandit -r . -f html -o rapport_bandit.html || true

      - name: Sauvegarde du rapport Bandit en artefact
        uses: actions/upload-artifact@v4
        with:
          name: rapport-bandit
          path: rapport_bandit.txt
          path: rapport_bandit.html
